name: Release

on:
  pull_request:
    types: [closed]

concurrency:
  group: release

jobs:
  release:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: Build & Zip exe
        id: build_zip
        shell: powershell
        run: |
          python build.py
          $version = python -c "from src import __version__; print(__version__)"
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          $folderName = "d4lf_v" + $version
          Compress-Archive -Path $folderName -DestinationPath "$folderName.zip"

      - name: Create Tag
        shell: powershell
        run: |
          git tag "v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"

      - name: Check if beta
        id: check_beta
        shell: powershell
        run: |
          if ("${{ env.VERSION }}".Contains("beta")) {
            echo "IS_BETA=true" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8
          } else {
            echo "IS_BETA=false" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8
          }

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: d4lf_v*.zip
          generate_release_notes: true
          prerelease: ${{ env.IS_BETA == 'true' }}
